// This code was generated by the Gardens Point Parser Generator
// Copyright (c) Wayne Kelly, QUT 2005-2010
// (see accompanying GPPGcopyright.rtf)

// GPPG version 1.5.0
// Machine:  CELESTINO
// DateTime: 28/06/2013 09.08.03
// UserName: Alessio
// Input file <D:\Dropbox\Progetti\C#\DanglingLang\DanglingLang\Tokenizer/DanglingLang.y - 29/05/2013 11.06.10>

// options: lines report gplex

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using QUT.Gppg;

namespace DanglingLang.Tokenizer
{
public enum Tokens {
    error=127,EOF=128,NUM=129,ID=130,MAX=131,NEWLINE=132,
    IF=133,PRINT=134,TRUE=135,FALSE=136,AND=137,EQUAL=138,
    LESS_THAN=139,LEQ=140,OR=141,UMINUS=142,MIN=143};

public struct ValueType
#line 2 "D:\Dropbox\Progetti\C#\DanglingLang\DanglingLang\Tokenizer/DanglingLang.y"
{
#line 3 "D:\Dropbox\Progetti\C#\DanglingLang\DanglingLang\Tokenizer/DanglingLang.y"
	internal int intValue;
#line 4 "D:\Dropbox\Progetti\C#\DanglingLang\DanglingLang\Tokenizer/DanglingLang.y"
	internal string identifier;
#line 5 "D:\Dropbox\Progetti\C#\DanglingLang\DanglingLang\Tokenizer/DanglingLang.y"
	internal Exp exp;
#line 6 "D:\Dropbox\Progetti\C#\DanglingLang\DanglingLang\Tokenizer/DanglingLang.y"
	internal Stmt stmt;
#line 7 "D:\Dropbox\Progetti\C#\DanglingLang\DanglingLang\Tokenizer/DanglingLang.y"
	internal List<Stmt> stmts;
#line 8 "D:\Dropbox\Progetti\C#\DanglingLang\DanglingLang\Tokenizer/DanglingLang.y"
}
// Abstract base class for GPLEX scanners
public abstract class ScanBase : AbstractScanner<ValueType,LexLocation> {
  private LexLocation __yylloc = new LexLocation();
  public override LexLocation yylloc { get { return __yylloc; } set { __yylloc = value; } }
  protected virtual bool yywrap() { return true; }
}

// Utility class for encapsulating token information
public class ScanObj {
  public int token;
  public ValueType yylval;
  public LexLocation yylloc;
  public ScanObj( int t, ValueType val, LexLocation loc ) {
    this.token = t; this.yylval = val; this.yylloc = loc;
  }
}

public class Parser: ShiftReduceParser<ValueType, LexLocation>
{
  // Verbatim content from D:\Dropbox\Progetti\C#\DanglingLang\DanglingLang\Tokenizer/DanglingLang.y - 29/05/2013 11.06.10
#line 27 "D:\Dropbox\Progetti\C#\DanglingLang\DanglingLang\Tokenizer/DanglingLang.y"
	internal Prog Prog;
  // End verbatim content from D:\Dropbox\Progetti\C#\DanglingLang\DanglingLang\Tokenizer/DanglingLang.y - 29/05/2013 11.06.10

#pragma warning disable 649
  private static Dictionary<int, string> aliasses;
#pragma warning restore 649
  private static Rule[] rules = new Rule[28];
  private static State[] states = new State[60];
  private static string[] nonTerms = new string[] {
      "exp", "stmt", "stmts", "prog", "$accept", };

  static Parser() {
    states[0] = new State(-3,new int[]{-4,1,-3,3});
    states[1] = new State(new int[]{128,2});
    states[2] = new State(-1);
    states[3] = new State(new int[]{132,5,129,26,135,27,136,28,43,29,131,31,40,37,130,43,126,41,123,47,133,50,134,55,128,-2},new int[]{-2,4,-1,6});
    states[4] = new State(-4);
    states[5] = new State(-5);
    states[6] = new State(new int[]{132,7,43,8,45,10,42,12,47,14,37,16,94,18,137,20,138,22,139,24});
    states[7] = new State(-6);
    states[8] = new State(new int[]{129,26,135,27,136,28,43,29,131,31,40,37,130,40,126,41},new int[]{-1,9});
    states[9] = new State(new int[]{43,-14,45,-14,42,12,47,14,37,16,94,18,137,-14,138,-14,139,-14,132,-14,44,-14,41,-14});
    states[10] = new State(new int[]{129,26,135,27,136,28,43,29,131,31,40,37,130,40,126,41},new int[]{-1,11});
    states[11] = new State(new int[]{43,-15,45,-15,42,12,47,14,37,16,94,18,137,-15,138,-15,139,-15,132,-15,44,-15,41,-15});
    states[12] = new State(new int[]{129,26,135,27,136,28,43,29,131,31,40,37,130,40,126,41},new int[]{-1,13});
    states[13] = new State(new int[]{43,-16,45,-16,42,-16,47,-16,37,-16,94,18,137,-16,138,-16,139,-16,132,-16,44,-16,41,-16});
    states[14] = new State(new int[]{129,26,135,27,136,28,43,29,131,31,40,37,130,40,126,41},new int[]{-1,15});
    states[15] = new State(new int[]{43,-17,45,-17,42,-17,47,-17,37,-17,94,18,137,-17,138,-17,139,-17,132,-17,44,-17,41,-17});
    states[16] = new State(new int[]{129,26,135,27,136,28,43,29,131,31,40,37,130,40,126,41},new int[]{-1,17});
    states[17] = new State(new int[]{43,-18,45,-18,42,-18,47,-18,37,-18,94,18,137,-18,138,-18,139,-18,132,-18,44,-18,41,-18});
    states[18] = new State(new int[]{129,26,135,27,136,28,43,29,131,31,40,37,130,40,126,41},new int[]{-1,19});
    states[19] = new State(new int[]{43,-20,45,-20,42,-20,47,-20,37,-20,94,18,137,-20,138,-20,139,-20,132,-20,44,-20,41,-20});
    states[20] = new State(new int[]{129,26,135,27,136,28,43,29,131,31,40,37,130,40,126,41},new int[]{-1,21});
    states[21] = new State(new int[]{43,8,45,10,42,12,47,14,37,16,94,18,137,-25,138,22,139,24,132,-25,44,-25,41,-25});
    states[22] = new State(new int[]{129,26,135,27,136,28,43,29,131,31,40,37,130,40,126,41},new int[]{-1,23});
    states[23] = new State(new int[]{43,8,45,10,42,12,47,14,37,16,94,18,137,-26,138,-26,139,24,132,-26,44,-26,41,-26});
    states[24] = new State(new int[]{129,26,135,27,136,28,43,29,131,31,40,37,130,40,126,41},new int[]{-1,25});
    states[25] = new State(new int[]{43,8,45,10,42,12,47,14,37,16,94,18,137,-27,138,-27,139,-27,132,-27,44,-27,41,-27});
    states[26] = new State(-11);
    states[27] = new State(-12);
    states[28] = new State(-13);
    states[29] = new State(new int[]{129,26,135,27,136,28,43,29,131,31,40,37,130,40,126,41},new int[]{-1,30});
    states[30] = new State(new int[]{43,-19,45,-19,42,-19,47,-19,37,-19,94,18,137,-19,138,-19,139,-19,132,-19,44,-19,41,-19});
    states[31] = new State(new int[]{40,32});
    states[32] = new State(new int[]{129,26,135,27,136,28,43,29,131,31,40,37,130,40,126,41},new int[]{-1,33});
    states[33] = new State(new int[]{44,34,43,8,45,10,42,12,47,14,37,16,94,18,137,20,138,22,139,24});
    states[34] = new State(new int[]{129,26,135,27,136,28,43,29,131,31,40,37,130,40,126,41},new int[]{-1,35});
    states[35] = new State(new int[]{41,36,43,8,45,10,42,12,47,14,37,16,94,18,137,20,138,22,139,24});
    states[36] = new State(-21);
    states[37] = new State(new int[]{129,26,135,27,136,28,43,29,131,31,40,37,130,40,126,41},new int[]{-1,38});
    states[38] = new State(new int[]{41,39,43,8,45,10,42,12,47,14,37,16,94,18,137,20,138,22,139,24});
    states[39] = new State(-22);
    states[40] = new State(-23);
    states[41] = new State(new int[]{129,26,135,27,136,28,43,29,131,31,40,37,130,40,126,41},new int[]{-1,42});
    states[42] = new State(-24);
    states[43] = new State(new int[]{61,44,132,-23,43,-23,45,-23,42,-23,47,-23,37,-23,94,-23,137,-23,138,-23,139,-23});
    states[44] = new State(new int[]{129,26,135,27,136,28,43,29,131,31,40,37,130,40,126,41},new int[]{-1,45});
    states[45] = new State(new int[]{132,46,43,8,45,10,42,12,47,14,37,16,94,18,137,20,138,22,139,24});
    states[46] = new State(-7);
    states[47] = new State(-3,new int[]{-3,48});
    states[48] = new State(new int[]{125,49,132,5,129,26,135,27,136,28,43,29,131,31,40,37,130,43,126,41,123,47,133,50,134,55},new int[]{-2,4,-1,6});
    states[49] = new State(-8);
    states[50] = new State(new int[]{40,51});
    states[51] = new State(new int[]{129,26,135,27,136,28,43,29,131,31,40,37,130,40,126,41},new int[]{-1,52});
    states[52] = new State(new int[]{41,53,43,8,45,10,42,12,47,14,37,16,94,18,137,20,138,22,139,24});
    states[53] = new State(new int[]{132,5,129,26,135,27,136,28,43,29,131,31,40,37,130,43,126,41,123,47,133,50,134,55},new int[]{-2,54,-1,6});
    states[54] = new State(-9);
    states[55] = new State(new int[]{40,56});
    states[56] = new State(new int[]{129,26,135,27,136,28,43,29,131,31,40,37,130,40,126,41},new int[]{-1,57});
    states[57] = new State(new int[]{41,58,43,8,45,10,42,12,47,14,37,16,94,18,137,20,138,22,139,24});
    states[58] = new State(new int[]{132,59});
    states[59] = new State(-10);

    for (int sNo = 0; sNo < states.Length; sNo++) states[sNo].number = sNo;

    rules[1] = new Rule(-5, new int[]{-4,128});
    rules[2] = new Rule(-4, new int[]{-3});
    rules[3] = new Rule(-3, new int[]{});
    rules[4] = new Rule(-3, new int[]{-3,-2});
    rules[5] = new Rule(-2, new int[]{132});
    rules[6] = new Rule(-2, new int[]{-1,132});
    rules[7] = new Rule(-2, new int[]{130,61,-1,132});
    rules[8] = new Rule(-2, new int[]{123,-3,125});
    rules[9] = new Rule(-2, new int[]{133,40,-1,41,-2});
    rules[10] = new Rule(-2, new int[]{134,40,-1,41,132});
    rules[11] = new Rule(-1, new int[]{129});
    rules[12] = new Rule(-1, new int[]{135});
    rules[13] = new Rule(-1, new int[]{136});
    rules[14] = new Rule(-1, new int[]{-1,43,-1});
    rules[15] = new Rule(-1, new int[]{-1,45,-1});
    rules[16] = new Rule(-1, new int[]{-1,42,-1});
    rules[17] = new Rule(-1, new int[]{-1,47,-1});
    rules[18] = new Rule(-1, new int[]{-1,37,-1});
    rules[19] = new Rule(-1, new int[]{43,-1});
    rules[20] = new Rule(-1, new int[]{-1,94,-1});
    rules[21] = new Rule(-1, new int[]{131,40,-1,44,-1,41});
    rules[22] = new Rule(-1, new int[]{40,-1,41});
    rules[23] = new Rule(-1, new int[]{130});
    rules[24] = new Rule(-1, new int[]{126,-1});
    rules[25] = new Rule(-1, new int[]{-1,137,-1});
    rules[26] = new Rule(-1, new int[]{-1,138,-1});
    rules[27] = new Rule(-1, new int[]{-1,139,-1});
  }

  protected override void Initialize() {
    this.InitSpecialTokens((int)Tokens.error, (int)Tokens.EOF);
    this.InitStates(states);
    this.InitRules(rules);
    this.InitNonTerminals(nonTerms);
  }

  protected override void DoAction(int action)
  {
#pragma warning disable 162, 1522
    switch (action)
    {
      case 2: // prog -> stmts
#line 30 "D:\Dropbox\Progetti\C#\DanglingLang\DanglingLang\Tokenizer/DanglingLang.y"
{ this.Prog = new Prog(ValueStack[ValueStack.Depth-1].stmts); }
        break;
      case 3: // stmts -> /* empty */
#line 33 "D:\Dropbox\Progetti\C#\DanglingLang\DanglingLang\Tokenizer/DanglingLang.y"
{ CurrentSemanticValue.stmts = new List<Stmt>(); }
        break;
      case 4: // stmts -> stmts, stmt
#line 34 "D:\Dropbox\Progetti\C#\DanglingLang\DanglingLang\Tokenizer/DanglingLang.y"
{ if ((ValueStack[ValueStack.Depth-1].stmt)!=null) ValueStack[ValueStack.Depth-2].stmts.Add(ValueStack[ValueStack.Depth-1].stmt); CurrentSemanticValue.stmts = ValueStack[ValueStack.Depth-2].stmts; }
        break;
      case 5: // stmt -> NEWLINE
#line 37 "D:\Dropbox\Progetti\C#\DanglingLang\DanglingLang\Tokenizer/DanglingLang.y"
{ CurrentSemanticValue.stmt = null; }
        break;
      case 6: // stmt -> exp, NEWLINE
#line 38 "D:\Dropbox\Progetti\C#\DanglingLang\DanglingLang\Tokenizer/DanglingLang.y"
{ CurrentSemanticValue.stmt = new EvalExp(ValueStack[ValueStack.Depth-2].exp); }
        break;
      case 7: // stmt -> ID, '=', exp, NEWLINE
#line 39 "D:\Dropbox\Progetti\C#\DanglingLang\DanglingLang\Tokenizer/DanglingLang.y"
{ CurrentSemanticValue.stmt = new Assignment(ValueStack[ValueStack.Depth-4].identifier, ValueStack[ValueStack.Depth-2].exp); }
        break;
      case 8: // stmt -> '{', stmts, '}'
#line 40 "D:\Dropbox\Progetti\C#\DanglingLang\DanglingLang\Tokenizer/DanglingLang.y"
{ CurrentSemanticValue.stmt = new Block(ValueStack[ValueStack.Depth-2].stmts); }
        break;
      case 9: // stmt -> IF, '(', exp, ')', stmt
#line 41 "D:\Dropbox\Progetti\C#\DanglingLang\DanglingLang\Tokenizer/DanglingLang.y"
{ CurrentSemanticValue.stmt = new If(ValueStack[ValueStack.Depth-3].exp, ValueStack[ValueStack.Depth-1].stmt ?? new Block(new List<Stmt>())); }
        break;
      case 10: // stmt -> PRINT, '(', exp, ')', NEWLINE
#line 42 "D:\Dropbox\Progetti\C#\DanglingLang\DanglingLang\Tokenizer/DanglingLang.y"
{ CurrentSemanticValue.stmt = new Print(ValueStack[ValueStack.Depth-3].exp); }
        break;
      case 11: // exp -> NUM
#line 45 "D:\Dropbox\Progetti\C#\DanglingLang\DanglingLang\Tokenizer/DanglingLang.y"
{ CurrentSemanticValue.exp = new IntLiteral(ValueStack[ValueStack.Depth-1].intValue); }
        break;
      case 12: // exp -> TRUE
#line 46 "D:\Dropbox\Progetti\C#\DanglingLang\DanglingLang\Tokenizer/DanglingLang.y"
{ CurrentSemanticValue.exp = new BoolLiteral(true); }
        break;
      case 13: // exp -> FALSE
#line 47 "D:\Dropbox\Progetti\C#\DanglingLang\DanglingLang\Tokenizer/DanglingLang.y"
{ CurrentSemanticValue.exp = new BoolLiteral(false); }
        break;
      case 14: // exp -> exp, '+', exp
#line 48 "D:\Dropbox\Progetti\C#\DanglingLang\DanglingLang\Tokenizer/DanglingLang.y"
{ CurrentSemanticValue.exp = new Sum(ValueStack[ValueStack.Depth-3].exp, ValueStack[ValueStack.Depth-1].exp); }
        break;
      case 15: // exp -> exp, '-', exp
#line 49 "D:\Dropbox\Progetti\C#\DanglingLang\DanglingLang\Tokenizer/DanglingLang.y"
{ CurrentSemanticValue.exp = new Subtraction(ValueStack[ValueStack.Depth-3].exp, ValueStack[ValueStack.Depth-1].exp); }
        break;
      case 16: // exp -> exp, '*', exp
#line 50 "D:\Dropbox\Progetti\C#\DanglingLang\DanglingLang\Tokenizer/DanglingLang.y"
{ CurrentSemanticValue.exp = new Product(ValueStack[ValueStack.Depth-3].exp, ValueStack[ValueStack.Depth-1].exp); }
        break;
      case 17: // exp -> exp, '/', exp
#line 51 "D:\Dropbox\Progetti\C#\DanglingLang\DanglingLang\Tokenizer/DanglingLang.y"
{ CurrentSemanticValue.exp = new Division(ValueStack[ValueStack.Depth-3].exp, ValueStack[ValueStack.Depth-1].exp); }
        break;
      case 18: // exp -> exp, '%', exp
#line 52 "D:\Dropbox\Progetti\C#\DanglingLang\DanglingLang\Tokenizer/DanglingLang.y"
{ CurrentSemanticValue.exp = new Remainder(ValueStack[ValueStack.Depth-3].exp, ValueStack[ValueStack.Depth-1].exp); }
        break;
      case 19: // exp -> '+', exp
#line 53 "D:\Dropbox\Progetti\C#\DanglingLang\DanglingLang\Tokenizer/DanglingLang.y"
{ CurrentSemanticValue.exp=ValueStack[ValueStack.Depth-1].exp; }
        break;
      case 20: // exp -> exp, '^', exp
#line 54 "D:\Dropbox\Progetti\C#\DanglingLang\DanglingLang\Tokenizer/DanglingLang.y"
{ CurrentSemanticValue.exp = new Power(ValueStack[ValueStack.Depth-3].exp, ValueStack[ValueStack.Depth-1].exp); }
        break;
      case 21: // exp -> MAX, '(', exp, ',', exp, ')'
#line 55 "D:\Dropbox\Progetti\C#\DanglingLang\DanglingLang\Tokenizer/DanglingLang.y"
{ CurrentSemanticValue.exp = new Max(ValueStack[ValueStack.Depth-4].exp, ValueStack[ValueStack.Depth-2].exp); }
        break;
      case 22: // exp -> '(', exp, ')'
#line 56 "D:\Dropbox\Progetti\C#\DanglingLang\DanglingLang\Tokenizer/DanglingLang.y"
{ CurrentSemanticValue.exp=ValueStack[ValueStack.Depth-2].exp; }
        break;
      case 23: // exp -> ID
#line 57 "D:\Dropbox\Progetti\C#\DanglingLang\DanglingLang\Tokenizer/DanglingLang.y"
{ CurrentSemanticValue.exp = new Id(ValueStack[ValueStack.Depth-1].identifier); }
        break;
      case 24: // exp -> '~', exp
#line 58 "D:\Dropbox\Progetti\C#\DanglingLang\DanglingLang\Tokenizer/DanglingLang.y"
{ CurrentSemanticValue.exp = new Not(ValueStack[ValueStack.Depth-1].exp); }
        break;
      case 25: // exp -> exp, AND, exp
#line 59 "D:\Dropbox\Progetti\C#\DanglingLang\DanglingLang\Tokenizer/DanglingLang.y"
{ CurrentSemanticValue.exp = new And(ValueStack[ValueStack.Depth-3].exp, ValueStack[ValueStack.Depth-1].exp); }
        break;
      case 26: // exp -> exp, EQUAL, exp
#line 60 "D:\Dropbox\Progetti\C#\DanglingLang\DanglingLang\Tokenizer/DanglingLang.y"
{ CurrentSemanticValue.exp = new Equal(ValueStack[ValueStack.Depth-3].exp, ValueStack[ValueStack.Depth-1].exp); }
        break;
      case 27: // exp -> exp, LESS_THAN, exp
#line 61 "D:\Dropbox\Progetti\C#\DanglingLang\DanglingLang\Tokenizer/DanglingLang.y"
{ CurrentSemanticValue.exp = new LessThan(ValueStack[ValueStack.Depth-3].exp, ValueStack[ValueStack.Depth-1].exp); }
        break;
    }
#pragma warning restore 162, 1522
  }

  protected override string TerminalToString(int terminal)
  {
    if (aliasses != null && aliasses.ContainsKey(terminal))
        return aliasses[terminal];
    else if (((Tokens)terminal).ToString() != terminal.ToString(CultureInfo.InvariantCulture))
        return ((Tokens)terminal).ToString();
    else
        return CharToString((char)terminal);
  }

#line 64 "D:\Dropbox\Progetti\C#\DanglingLang\DanglingLang\Tokenizer/DanglingLang.y"
	public Parser(Scanner s) : base(s) {}
}
}
